### ISSUE TITLE
Research Cloud Functions

### ISSUE THREAD

**Issue by alaq** [npm-install/summaries.io#9]
- Time-based trigger for the CF
- Email sent to registered users

**Comment by alaq** [comment]
Official tutorial: https://cloud.google.com/functions/docs/tutorials/sendgrid

**Comment by alaq** [comment]
there is no time based triggers for Firebase's cloud functions so we should follow the official recommandation: https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html

**Comment by alaq** [comment]
from @leahzxxz https://www.automationfuel.com/firebase-functions-sending-emails/

**Comment by mueedc-zz** [comment]
function triggers https://firebase.google.com/docs/functions/firestore-events?authuser=0

**Comment by alaq** [comment]
closing this, because it is making me angry
